### ISSUE TITLE
Migrate project to Kotlin

### ISSUE THREAD

**Issue by kingahmedino** [PatilShreyas/MaterialDialog-Android#34] opened 2020-10-09 14:49 UTC
I would like to contribute to this project by helping to migrate all existing Java code to Kotlin

**Comment by PatilShreyas** [comment] 2020-10-09 15:18
Thanks @kingahmedino for your thought on contributing to this project. Migration of this library to the Kotlin is already WIP. See https://github.com/PatilShreyas/MaterialDialog-Android/pull/33

**Comment by PatilShreyas** [comment] 2020-10-10 17:21
Duplicate of #32. You can refer this issue and PR #33

**Closed by PatilShreyas** 2020-10-10 17:21 UTC
